"""initial migration

Revision ID: 5f3139060348
Revises: 
Create Date: 2025-06-17 21:45:42.617896

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5f3139060348'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_order'), 'collection', ['order'], unique=True)
    op.create_index(op.f('ix_collection_title'), 'collection', ['title'], unique=True)
    op.create_table('product_category',
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('title_uk', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_en'),
    sa.UniqueConstraint('title_uk')
    )
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('collection_banner',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('device_type', sa.Enum('desktop', 'mobile', name='devicetype'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_banner_device_type'), 'collection_banner', ['device_type'], unique=False)
    op.create_table('product',
    sa.Column('sizes', sa.JSON(), nullable=True),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('title_uk', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description_uk', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('price_uah', sa.Float(), nullable=False),
    sa.Column('price_eur', sa.Float(), nullable=False),
    sa.Column('attachment', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category_id'), 'product', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_collection_id'), 'product', ['collection_id'], unique=False)
    op.create_index(op.f('ix_product_order'), 'product', ['order'], unique=True)
    op.create_table('product_images',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'order', name='unique_product_image_order')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_images')
    op.drop_index(op.f('ix_product_order'), table_name='product')
    op.drop_index(op.f('ix_product_collection_id'), table_name='product')
    op.drop_index(op.f('ix_product_category_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_collection_banner_device_type'), table_name='collection_banner')
    op.drop_table('collection_banner')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('product_category')
    op.drop_index(op.f('ix_collection_title'), table_name='collection')
    op.drop_index(op.f('ix_collection_order'), table_name='collection')
    op.drop_table('collection')
    # ### end Alembic commands ###
