"""switch description fields to type TEXT

Revision ID: 6f49de6806a0
Revises: ce49bceeb38c
Create Date: 2026-03-03 23:59:02.378322

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6f49de6806a0'
down_revision = 'ce49bceeb38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gift', 'description_en',
               existing_type=sa.VARCHAR(length=510),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('gift', 'description_uk',
               existing_type=sa.VARCHAR(length=510),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('product', 'description_en',
               existing_type=sa.VARCHAR(length=510),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('product', 'description_uk',
               existing_type=sa.VARCHAR(length=510),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'description_uk',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=510),
               existing_nullable=False)
    op.alter_column('product', 'description_en',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=510),
               existing_nullable=False)
    op.alter_column('gift', 'description_uk',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=510),
               existing_nullable=False)
    op.alter_column('gift', 'description_en',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=510),
               existing_nullable=False)
    # ### end Alembic commands ###
