"""add orders and gifts

Revision ID: bb65635d9495
Revises: 5f3139060348
Create Date: 2025-07-13 19:01:15.876847

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bb65635d9495'
down_revision = '5f3139060348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift',
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('title_uk', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(length=510), nullable=False),
    sa.Column('description_uk', sqlmodel.sql.sqltypes.AutoString(length=510), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('price_uah', sa.Float(), nullable=False),
    sa.Column('price_eur', sa.Float(), nullable=False),
    sa.Column('dynamic_price', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_order'), 'gift', ['order'], unique=True)
    op.create_table('order',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delivery_address', sa.JSON(), nullable=False),
    sa.Column('billing_address', sa.JSON(), nullable=True),
    sa.Column('shipping_method', sa.Enum('UPS_EXPRESS', 'NOVA_POST', name='shippingmethods'), nullable=False),
    sa.Column('mailing', sa.Boolean(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_status', sa.Enum('CREATED', 'PROCESSING', 'HOLD', 'SUCCESS', 'FAILURE', 'REVERSED', 'EXPIRED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('UAH', 'USD', 'EUR', name='currency'), nullable=False),
    sa.Column('basketOrder', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoiceId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoiceId')
    )
    op.create_table('gift_banner',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gift_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['gift_id'], ['gift.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('is_gift', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_gift')
    op.drop_table('gift_banner')
    op.drop_table('order')
    op.drop_index(op.f('ix_gift_order'), table_name='gift')
    op.drop_table('gift')
    # ### end Alembic commands ###
