"""update gift for multiple images

Revision ID: be4c4eef0493
Revises: 6f49de6806a0
Create Date: 2026-03-04 19:32:17.443950

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'be4c4eef0493'
down_revision = '6f49de6806a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_images',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gift_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gift_id'], ['gift.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gift_id', 'order', name='unique_gift_image_order')
    )
    op.drop_table('gift_banner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_banner',
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alt_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('gift_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['gift_id'], ['gift.id'], name='gift_banner_gift_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='gift_banner_pkey')
    )
    op.drop_table('gift_images')
    # ### end Alembic commands ###
