"""add in_stock and preorder fields in product

Revision ID: ce49bceeb38c
Revises: f637b54dda6d
Create Date: 2025-07-30 00:47:16.071634

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ce49bceeb38c'
down_revision = 'f637b54dda6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('in_stock', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('product', sa.Column('preorder', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'preorder')
    op.drop_column('product', 'in_stock')
    # ### end Alembic commands ###
