"""add gift occasion

Revision ID: f5dfed3fab5f
Revises: be4c4eef0493
Create Date: 2026-03-05 01:57:34.821035

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f5dfed3fab5f'
down_revision = 'be4c4eef0493'
branch_labels = None
depends_on = None

"""add gift occasion

Revision ID: 30ee4237e8f7
Revises: be4c4eef0493
Create Date: 2026-03-05 01:26:46.033020

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '30ee4237e8f7'
down_revision = 'be4c4eef0493'
branch_labels = None
depends_on = None


giftOccasion = sa.Enum(
    "STANDARD",
    "MARCH8",
    name="giftoccasion"
)


def upgrade():
    giftOccasion.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift', sa.Column('occasion', giftOccasion, nullable=False, server_default="STANDARD"))
    op.create_index(op.f('ix_gift_occasion'), 'gift', ['occasion'], unique=False)
    # ### end Alembic commands ###


def downgrade():    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gift_occasion'), table_name='gift')
    op.drop_column('gift', 'occasion')
    giftOccasion.drop(op.get_bind())
    # ### end Alembic commands ###