"""increase description max chars

Revision ID: f637b54dda6d
Revises: bb65635d9495
Create Date: 2025-07-17 01:26:40.528109

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f637b54dda6d'
down_revision = 'bb65635d9495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'description_en',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=510),
               existing_nullable=False)
    op.alter_column('product', 'description_uk',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=510),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'description_uk',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=510),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('product', 'description_en',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=510),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
